CREATE PROCEDURE [dbo].[SP_GetDateTimeByName]
AS
BEGIN
	SET NOCOUNT ON;
	--select CAST(GETDATE() AS CHAR(12)) Tanggal

	SELECT LEFT(RTRIM(LTRIM(RIGHT(CONVERT(VARCHAR(12), GETDATE(), 107), 9))),2) +' '+ DATENAME(MONTH, GETDATE()) +' '+ RIGHT(RTRIM(LTRIM(RIGHT(CONVERT(VARCHAR(12), GETDATE(), 107), 9))),4) AS Tanggal
END


