CREATE TABLE [dbo].[LogClosing] (
    [IdLog]                        BIGINT         IDENTITY (1, 1) NOT NULL,
    [Datetime]                     NVARCHAR (50)  NULL,
    [NamaComputer]                 NVARCHAR (MAX) NULL,
    [NamaUser]                     NVARCHAR (MAX) NULL,
    [TotalAllTicket]               FLOAT (53)     NULL,
    [TotalTransaksi]               FLOAT (53)     NULL,
    [TotalTopup]                   FLOAT (53)     NULL,
    [TotalRegis]                   FLOAT (53)     NULL,
    [TotalRefund]                  FLOAT (53)     NULL,
    [TotalFoodcourt]               FLOAT (53)     NULL,
    [TotalDanaModal]               FLOAT (53)     NULL,
    [TotalCashOut]                 FLOAT (53)     NULL,
    [TotalCashIn]                  FLOAT (53)     NULL,
    [TotalCashBox]                 FLOAT (53)     NULL,
    [TotalCashirInputMoneyCashbox] FLOAT (53)     NULL,
    [MinusIndikasiMoneyCashBox]    FLOAT (53)     NULL,
    [MatchingSucces]               NVARCHAR (MAX) NULL,
    [StatusAcceptanceBySPV]        NVARCHAR (MAX) NULL,
    [KeteranganAcceptance]         NVARCHAR (MAX) NULL,
    [UangDiterimaFinnance]         FLOAT (53)     NULL,
    [TotalTrxEdc]                  FLOAT (53)     NULL,
    [TotalNominalDebit]            FLOAT (53)     NULL,
    [TotalTrxEmoney]               FLOAT (53)     NULL,
    [TotalNominalDebitEmoney]      FLOAT (53)     NULL,
    [Status]                       INT            NOT NULL,
    [StatusUpload]                 INT            NULL
);

