CREATE TABLE [dbo].[LogRegistrasiDetail] (
    [idTrx]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [Datetime]           NVARCHAR (50)  NULL,
    [AccountNumber]      NVARCHAR (50)  NULL,
    [SaldoEmoney]        FLOAT (53)     NULL,
    [SaldoEmoneyAfter]   FLOAT (53)     NULL,
    [TicketWeekDay]      FLOAT (53)     NULL,
    [TicketWeekDayAfter] FLOAT (53)     NULL,
    [TicketWeekEnd]      FLOAT (53)     NULL,
    [TicketWeekEndAfter] FLOAT (53)     NULL,
    [SaldoJaminan]       FLOAT (53)     NULL,
    [SaldoJaminanAfter]  FLOAT (53)     NULL,
    [IdTicketTrx]        BIGINT         NULL,
    [Cashback]           FLOAT (53)     NULL,
    [Topup]              FLOAT (53)     NULL,
    [Asuransi]           FLOAT (53)     NULL,
    [QtyTotalTiket]      FLOAT (53)     NULL,
    [TotalBeliTiket]     FLOAT (53)     NULL,
    [TotalAll]           FLOAT (53)     NULL,
    [JenisTransaksi]     NVARCHAR (MAX) NULL,
    [TotalBayar]         FLOAT (53)     NULL,
    [PayEmoney]          FLOAT (53)     NULL,
    [PayCash]            FLOAT (53)     NULL,
    [TerimaUang]         FLOAT (53)     NULL,
    [Kembalian]          FLOAT (53)     NULL,
    [CashierBy]          NVARCHAR (MAX) NULL,
    [ComputerName]       NVARCHAR (MAX) NULL,
    [status]             INT            NULL,
    [IdLogEDCTransaksi]  BIGINT         NULL,
    [BankCode]           NVARCHAR (50)  NULL,
    [NamaBank]           NVARCHAR (MAX) NULL,
    [DiskonBank]         FLOAT (53)     NULL,
    [NominalDiskon]      FLOAT (53)     NULL,
    [AdminCharges]       FLOAT (53)     NULL,
    [TotalDebit]         FLOAT (53)     NULL,
    [StatusUpload]       INT            NULL
);

